Social/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Social.Models
{
    public class Login
    {
        
        [Required]
        public string Username { get; set; }
        
        [Required]
        public string Password { get; set; }

    }
}

Social/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Social.Models;
using WebMatrix.WebData;
using WebMatrix.Data;
using Microsoft.AspNet.Identity;
using Authentication;
using Microsoft.Owin.Security;

namespace Social.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        
        //private IUserProfileContext context = null;

        private readonly IAuthenticationManager _authenticationManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserStore<ApplicationUser> _userStore;

        public DashboardController(IUserProfileContext dataContext, 
            IUserStore<ApplicationUser> userStore,
            IAuthenticationManager authenticationManager)
        {
            //this.context = dataContext;

            _userManager = new UserManager<ApplicationUser>(userStore);
            _authenticationManager = authenticationManager;
            _userStore = userStore;
        }

        public ActionResult Index()
        {
            //IEnumerable<UserProfile> list = context.UserProfile;

            IEnumerable<ApplicationUser> list = _userManager.Users;

            return View(list);
        }

        public JsonResult GetLastUser()
        {

            //List<AppUser> json = new List<AppUser>(); //context.UserProfile;

            //json.Add(new AppUser { UserName = "Jonny", LastName = "Begood" });
            var json = _userManager.Users.ToList();
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetLastUserOnly()
        {
            //var json = context.UserProfile.Where(e=>e.Id== WebSecurity.CurrentUserId);
            //return Json(json, JsonRequestBehavior.AllowGet);
            return Json(null);
        }

	}
}

Social/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Social.Models;
using WebMatrix.WebData;
using System.Data.Entity;
using Microsoft.Owin.Security;
using Authentication;
using Microsoft.AspNet.Identity;

namespace Social.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IAuthenticationManager _authenticationManager;
        private readonly UserManager<ApplicationUser> _userManager;
        //private readonly IUserProfileContext context = null;
        private readonly IUserStore<ApplicationUser> _userStore;

        public ProfileController(IUserProfileContext dataContext,IUserStore<ApplicationUser> userStore, 
            IAuthenticationManager authenticationManager)
        {
            //this.context = dataContext;
            _userManager = new UserManager<ApplicationUser>(userStore);
            _authenticationManager = authenticationManager;
            this._userStore = userStore;

        }
        
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult UserProfile()
        {
            //UserProfile profile = context.UserProfile.Where(p => p.UserId == WebSecurity.CurrentUserId).SingleOrDefault();
            //string id = _userManager.FindByName(User.Identity.Name).;
            ApplicationUser user = _userManager.FindByName(User.Identity.Name);
            //Response.Write(user.LastName);
            return View(user);
            //return View(profile);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserProfile(ApplicationUser model )
        {
            if (ModelState.IsValid)
            {
                //ApplicationUser profileToUpdate = _userManager.FindByName(User.Identity.Name); //context.UserProfile.Where(p => p.UserId == WebSecurity.CurrentUserId).SingleOrDefault();

                ////UpdateModel(profileToUpdate);
                //_userManager.Update(profileToUpdate);
                
                ////context.SaveChanges();
                return View(model);
            }
            else
            {
                
                return View(model);
            }
        }

        [Authorize]
        [HttpPost]
        public JsonResult Update(ApplicationUser user)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser profileToUpdate = _userManager.FindByName(user.UserName);
                
                profileToUpdate.FirstName = user.FirstName;
                profileToUpdate.LastName = user.LastName;
                profileToUpdate.Email = user.Email;
                profileToUpdate.Address = user.Address;

                _userManager.Update(profileToUpdate);
                //UpdateModel(profileToUpdate);
                
                //context.SaveChanges();
                return Json(profileToUpdate);
            }
            else
            {

                return Json(user);
            }
        }


        public JsonResult GetProfile()
        {
            var json = _userManager.FindByName(User.Identity.Name);

            return Json(json, JsonRequestBehavior.AllowGet);
        }


	}
}

Social/Controllers/WeatherServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Social.Controllers
{
    public class WeatherServiceController : Controller
    {

        
        
        public readonly IWeatherService weatherService = null;


        public WeatherServiceController(): base() { }


        public WeatherServiceController(IWeatherService tempWeatherService)
        {
            this.weatherService = tempWeatherService;
        }



        public ActionResult Index()
        {
            string content = weatherService.getWeather();
            ViewBag.Weather = content;
            return View();
        }
	}
}

Social/Views/Shared/_Dialog.cshtml
<div> <!--ng-controller="DialogController"-->

    <script type="text/ng-template" id="myModalContent.html">
        <div class="modal-header">
            <h3 class="modal-title">{{items.FirstName}}</h3>
        </div>

        <img height="100px" style="float:right;" ng-src="{{items.ProfilePicture}}" />


        <div class="modal-body">
            <!--
            <ul>
                
                <li class="labelData"><span>FirstName:</span><a ng-click="selected.item = items.FirstName">FirstName:{{items.FirstName}}</a></li>
                <li class="labelData"><span>LastName:</span><a ng-click="selected.item = items.LastName">LastName:{{items.LastName}}</a></li>
                <li class="labelData"><span>EMail:</span><a ng-click="selected.item = items.Email">E-Mail:{{items.Email}}</a></li>
            </ul>
            -->

            <table style="font-size:18px">
                <tr>
                    <td class="labelData">FirstName:</td> <td class="data" ng-click="selected.item = items.FirstName">{{items.FirstName}}</td>
                </tr>
                <tr>
                    <td class="labelData">LastName:</td><td class="data" ng-click="selected.item = items.LastName">{{items.LastName}}</td>
                </tr>
                <tr>
                    <td class="labelData">EMail:</td><td class="data" ng-click="selected.item = items.Email">{{items.Email}}</td>
                </tr>
            </table>
            <br />
            
            Selected: <b>{{ selected.item}}</b>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" ng-click="ok()">Save</button>
            <button class="btn btn-primary" ng-click="cancel()">Cancel</button>
        </div>
    </script>

    <style>
        .labelData {
            width:150px;
            font-weight:bold;
        }

        .data
        {
            color:#245580;
            cursor:pointer;
        }

    </style>
    <!--
    <button class="btn btn-default" ng-click="open()">Open me!</button>
    <button class="btn btn-default" ng-click="open('lg')">Large modal</button>
    <button class="btn btn-default" ng-click="open('sm')">Small modal</button>
    <button class="btn btn-default" ng-click="toggleAnimation()">Toggle Animation ({{ animationsEnabled }})</button>
    <div ng-show="selected">Selection from a modal: {{ selected }}</div>
        -->
</div>

Social/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    


   
</head>
<body ng-app="MyApp">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Social", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    @if(!User.Identity.IsAuthenticated)
                    { 
                        <li>@Html.ActionLink("Login","Login","Account")</li>
                        <li>@Html.ActionLink("Register", "Register", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("MyDashBoard","Index","Dashboard")</li>
                        <li>@Html.ActionLink("MyProfile", "UserProfile", "Profile")</li>
                        @*<li>@Html.ActionLink("Logout " + User.Identity.Name ,"Logout","Account")</li>*@
                    }
                    
                    <li>@Html.ActionLink("Wizard", "Index", "Wizard")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Weather", "Index", "WeatherService")</li>
                    <li>@Html.ActionLink("CYDE", "Index", "CYDE")</li>


                    @if (User.Identity.IsAuthenticated)
                    { 
                        
                            @Html.Partial("_MenuButton")
                        
                    }
                </ul>

                <div>

                    @if (!User.Identity.IsAuthenticated)
                    {
    
                    }
                    else
                    {
                        
                    }

                </div>
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Social Media</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/angular")

    @Scripts.Render("~/bundles/app") @* Main Angular App Instance instead of including <script src="~/App/MyApp.js"></script>*@
    @Scripts.Render("~/bundles/menu")

    
    @Scripts.Render("~/bundles/bootstrap")
    


    @RenderSection("scripts", required: false)

    
    

</body>
</html>

Social/Views/Shared/_Login.cshtml
@model Social.Models.Login

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Username, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Username, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Username)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Social/Views/Shared/_MenuButton.cshtml
<div ng-controller="MenuController" class="btn-group" dropdown is-open="status.isopen" style="padding: 7px;">
    <button type="button" class="btn btn-primary dropdown-toggle" dropdown-toggle ng-disabled="disabled">
        Account <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li>@Html.ActionLink("MyProfile", "UserProfile", "Profile")</li>
        <li><a href="#" ng-click="menuClicked()">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li class="divider"></li>
        <li>@Html.ActionLink("Logout " + User.Identity.Name, "Logout", "Account")</li>
    </ul>
</div>

Social/Views/Shared/_UserProfile.cshtml
@model Social.Models.UserProfile
<tr>
    <td>
        @Html.DisplayFor(modelItem => modelItem.Username)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.FirstName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.LastName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.Address)
    </td>
    <td>
        <!-- @Html.ActionLink("Add Friend", "Edit", new { id = @Model.UserId }) -->
        <button id="btn" class="form-control">Add Friend</button>
    </td>
</tr>